name       : python-black
version    : 22.3.0
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/b/black/black-22.3.0.tar.gz : 35020b8886c022ced9282b51b5a875b6d1ab0c387b31a065b84db7c33085ca79
homepage   : https://github.com/psf/black
license    : MIT
component  : programming.python
summary    : The uncompromising Python code formatter
description: |
    Black is the uncompromising Python code formatter. By using it, you agree to cede control over minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters.
builddeps  :
    - python-setuptools-scm
rundeps    :
    - python-click
    - python-mypy_extensions
    - python-pathspec
    - python-platformdirs
    - python-tomli
    - python-typing-extensions
build      : |
    %python3_setup
install    : |
    %python3_install
