name       : python-black
version    : 22.12.0
release    : 11
source     :
    - https://files.pythonhosted.org/packages/source/b/black/black-22.12.0.tar.gz : 229351e5a18ca30f447bf724d007f890f97e13af070bb6ad4c0a441cd7596a2f
homepage   : https://github.com/psf/black
license    : MIT
component  : programming.python
summary    : The uncompromising Python code formatter
description: |
    Black is the uncompromising Python code formatter. By using it, you agree to cede control over minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters.
builddeps  :
    - python-build
    - python-hatch-fancy-pypi-readme
    - python-hatch-vcs
    - python-installer
rundeps    :
    - python-click
    - python-mypy_extensions
    - python-pathspec
    - python-platformdirs
    - python-tomli
    - python-typing-extensions
build      : |
    %python3_setup
install    : |
    %python3_install
