name       : python-black
version    : '20.8_1'
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/b/black/black-20.8b1.tar.gz : 1c02557aa099101b9d21496f8a914e9ed2222ef70336404eeeac8edba836fbea
homepage   : https://github.com/psf/black
license    : MIT
component  : programming.python
summary    : The uncompromising Python code formatter
description: |
    Black is the uncompromising Python code formatter. By using it, you agree to cede control over minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters.
builddeps  :
    - python-setuptools-scm
rundeps    :
    - python-click
    - python-mypy_extensions
    - python-pathspec
    - python-regex
    - python-toml
    - python-typed-ast
    - python-typing-extensions
build      : |
    %python3_setup
install    : |
    %python3_install
