name       : python-black
version    : 21.6_0b
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/b/black/black-21.6b0.tar.gz : dc132348a88d103016726fe360cb9ede02cecf99b76e3660ce6c596be132ce04
homepage   : https://github.com/psf/black
license    : MIT
component  : programming.python
summary    : The uncompromising Python code formatter
description: |
    Black is the uncompromising Python code formatter. By using it, you agree to cede control over minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters.
builddeps  :
    - python-setuptools-scm
rundeps    :
    - python-click
    - python-mypy_extensions
    - python-pathspec
    - python-regex
    - python-toml
    - python-typed-ast
    - python-typing-extensions
build      : |
    %python3_setup
install    : |
    %python3_install
