name       : python-black
version    : 22.6.0
release    : 9
source     :
    - https://files.pythonhosted.org/packages/source/b/black/black-22.6.0.tar.gz : 6c6d39e28aed379aec40da1c65434c77d75e65bb59a1e1c283de545fb4e7c6c9
homepage   : https://github.com/psf/black
license    : MIT
component  : programming.python
summary    : The uncompromising Python code formatter
description: |
    Black is the uncompromising Python code formatter. By using it, you agree to cede control over minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters.
builddeps  :
    - python-setuptools-scm
rundeps    :
    - python-click
    - python-mypy_extensions
    - python-pathspec
    - python-platformdirs
    - python-tomli
    - python-typing-extensions
build      : |
    %python3_setup
install    : |
    %python3_install
