name       : python-black
version    : 22.10.0
release    : 10
source     :
    - https://files.pythonhosted.org/packages/source/b/black/black-22.10.0.tar.gz : f513588da599943e0cde4e32cc9879e825d58720d6557062d1098c5ad80080e1
homepage   : https://github.com/psf/black
license    : MIT
component  : programming.python
summary    : The uncompromising Python code formatter
description: |
    Black is the uncompromising Python code formatter. By using it, you agree to cede control over minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters.
builddeps  :
    - python-build
    - python-hatch-fancy-pypi-readme
    - python-hatch-vcs
    - python-installer
rundeps    :
    - python-click
    - python-mypy_extensions
    - python-pathspec
    - python-platformdirs
    - python-tomli
    - python-typing-extensions
build      : |
    %python3_setup
install    : |
    %python3_install
